In [1]:
import pandas as pd
import numpy as np

**Q1: What is version of Pandas?** *Answer: Installed version is 2.3.1*

In [2]:
pd.__version__

'2.3.1'

**Q2: How many records are in the downloaded dataset?** *Answer: there are 9704 records in the dataset*

In [3]:
df = pd.read_csv('car_fuel_efficiency.txt')

In [6]:
df.shape

(9704, 11)

**Q3: How many fuel types??**  *Answer: there are 2 fuel types in the dataset*

In [8]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

**Q4: How many columns have missing values?**   *Answer: 4 columns have missing values*

In [12]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

**Q5: What is the max fuel efficiency of cars from Asia?** *Answer: the answer is 23.76 (23.75 since that is the closest option provided)*

In [16]:
df.groupby('origin')['fuel_efficiency_mpg'].max().round(2)

origin
Asia      23.76
Europe    25.97
USA       24.97
Name: fuel_efficiency_mpg, dtype: float64

**Q6: Median value of horsepower...does filling in missing data change it?** *Answer: yes, it increased (unsurprising since the most common value was more than the median and was used to fill more than 700 missing values)*

In [17]:
df.horsepower.median()

np.float64(149.0)

In [21]:
df.horsepower.value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [22]:
df_filled = df.fillna({'horsepower':152})

In [25]:
df_filled.horsepower.median()

np.float64(152.0)

**Q7: Sum of weights...what is the sum?** *Answer:.51*

In [38]:
X = df[df.origin == 'Asia'][['vehicle_weight','model_year']].head(n=7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [47]:
X_transpose = X.T
XTX = X_transpose.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [49]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [51]:
y = np.array([1100,1300,800,900,1000,1100,1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [58]:
w=XTX_inv.dot(X_transpose).dot(y)
w.sum()

np.float64(0.5187709081074016)