In [1]:
import numpy as np

In [12]:
def vect_vect_mult (u,v):
    assert u.shape[0] == v.shape[0]

    result = 0.0
    for i in range(u.shape[0]):
        result += u[i] * v[i]

    return result


In [15]:
x = np.array([2,4,5])

In [16]:
vect_vect_mult(u,x)

AssertionError: 

In [20]:
U = np.array ([
    [2,4,5,6],
    [1,2,1,2],
    [3,2,1,2]
])

In [22]:
v = np.array ([1,.5,2,1])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
2 * vect

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [18]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [8]:
v.transpose() * u

array([ 2,  0,  0, 12])

In [11]:
v.transpose().shape

(4,)

In [4]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
constant_array = np.full(10,3)

In [7]:
my_list = [2,3,4]
np.array(my_list)

array([2, 3, 4])

In [8]:
array_from_list = np.arange(9)

In [9]:
array_from_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
linspace_array = np.linspace(0,1,11)

In [11]:
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
zeros_matrix = np.zeros((5,2))

In [13]:
zeros_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.random.seed(2)
rand_array = np.random.rand(5,2)

In [15]:
rand_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [16]:
zeros_matrix = zeros_matrix + 1

In [17]:
zeros_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
zeros_matrix = zeros_matrix + np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [19]:
np.random.randint(100)

37

In [20]:
zeros_matrix = zeros_matrix + np.random.randint(100)

In [21]:
zeros_matrix

array([[40., 40.],
       [40., 40.],
       [40., 40.],
       [40., 40.],
       [40., 40.]])